# Generated by Django 3.1.4 on 2022-10-18 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bezeroa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('izena', models.CharField(max_length=50)),
                ('abizena', models.CharField(max_length=50)),
                ('zb', models.CharField(max_length=9)),
                ('alokatu', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Kotxea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matrikula', models.CharField(max_length=8)),
                ('marka', models.CharField(max_length=100)),
                ('alokatuHasiera', models.DateTimeField()),
                ('alokatuAmaiera', models.DateField()),
                ('bezeroa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kotxeak.bezeroa')),
            ],
        ),
    ]
