# Generated by Django 3.1.4 on 2022-10-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kotxeak', '0002_remove_bezeroa_alokatu'),
    ]

    operations = [
        migrations.CreateModel(
            name='KotxeaSortzekoModeloa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matrikula', models.CharField(max_length=8)),
                ('marka', models.CharField(max_length=100)),
            ],
        ),
    ]
