# Generated by Django 3.1.4 on 2022-10-18 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kotxeak', '0003_kotxeasortzekomodeloa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kotxea',
            name='marka',
        ),
        migrations.RemoveField(
            model_name='kotxea',
            name='matrikula',
        ),
        migrations.AddField(
            model_name='kotxea',
            name='kotxea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kotxeak.kotxeasortzekomodeloa'),
        ),
    ]
