# Generated by Django 3.1.4 on 2022-10-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kotxeak', '0004_auto_20221018_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kotxea',
            name='alokatuAmaiera',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='kotxea',
            name='alokatuHasiera',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
